name: Update README stats

# ← ここ大事：Actionsに書き込み権限を明示
permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
    paths:
      - "notes/**"
      - "README.md"
      - ".github/workflows/update-readme.yml"
  workflow_dispatch: {}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # デフォルト資格情報を保持（push可）

      - name: Count notes & update README
        shell: bash
        run: |
          set -euo pipefail
          COUNT=$(find notes -type f -name 'note-*.md' 2>/dev/null | wc -l | tr -d ' ')
          LAST=$(ls -1 notes/note-*.md 2>/dev/null | sed -E 's#.*/note-([0-9]{4}-[0-9]{2}-[0-9]{2}).*#\1#' | sort | tail -n1)
          [[ -z "${LAST}" ]] && LAST="N/A"

          tmpfile=$(mktemp)
          awk -v c="$COUNT" -v d="$LAST" '
            { gsub("<!-- NOTES_COUNT -->[^<]*<!-- NOTES_COUNT -->","<!-- NOTES_COUNT -->" c "<!-- NOTES_COUNT -->");
              gsub("<!-- LAST_UPDATED -->[^<]*<!-- LAST_UPDATED -->","<!-- LAST_UPDATED -->" d "<!-- LAST_UPDATED -->");
              print }' README.md > "$tmpfile"
          mv "$tmpfile" README.md

          if ! git diff --quiet README.md; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "chore: update README stats (notes=${COUNT}, last=${LAST})"
          fi

      - name: Push changes
        run: git push
