name: Update README stats

on:
  push:
    branches: [ "main" ]
    paths:
      - "notes/**"
      - "README.md"
      - ".github/workflows/update-readme.yml"
  workflow_dispatch: {}  # 手動実行も可（Actionsタブから）

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # リポジトリを取得

      - name: Count notes & update README
        shell: bash
        run: |
          set -euo pipefail

          # ノート数を数える（notes/note-YYYY-MM-DD.md 前提）
          COUNT=$(find notes -type f -name 'note-*.md' 2>/dev/null | wc -l | tr -d ' ')
          # 最新日付をファイル名から抽出
          LAST=$(ls -1 notes/note-*.md 2>/dev/null | sed -E 's#.*/note-([0-9]{4}-[0-9]{2}-[0-9]{2}).*#\1#' | sort | tail -n1)
          [[ -z "${LAST}" ]] && LAST="N/A"

          # README内のプレースホルダを書き換え
          tmpfile=$(mktemp)
          awk -v c="$COUNT" -v d="$LAST" '
            { gsub("<!-- NOTES_COUNT -->[^<]*<!-- NOTES_COUNT -->","<!-- NOTES_COUNT -->" c "<!-- NOTES_COUNT -->");
              gsub("<!-- LAST_UPDATED -->[^<]*<!-- LAST_UPDATED -->","<!-- LAST_UPDATED -->" d "<!-- LAST_UPDATED -->");
              print }' README.md > "$tmpfile"
          mv "$tmpfile" README.md

          # 変更があるときだけコミット
          if ! git diff --quiet README.md; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "chore: update README stats (notes=$COUNT, last=$LAST)"
          fi

      - name: Push changes
        run: git push
